name: 'Dockerize'ainer Registry, and Cosign. It ensures secure and versioned deployments for containerized applications.'
inputs:
  docker_directory:
    description: 'The directory containing the Dockerfile'
    required: true
    default: '.'
    type: string
  image_name:
    description: 'The name of the Docker image'
    required: true
    default: null
    type: string
  platform:
    description: 'The platform to build the Docker image for'
    required: true
    # linux/amd64,linux/arm64
    default: 'linux/amd64'
    type: string
outputs:
  image_name:
    description: 'The name of the Docker image'
    value: 'toto'

runs:
  using: 'composite'
  steps:

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.7.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.3.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.8.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5.6.1
      with:
        images: ghcr.io/${{ inputs.image_name }}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v6.13.0
      with:
        context: ${{ env.PROMETHEUS_DIRECTORY }}
        push: ${{ github.event_name != 'pull_request' }}
        provenance: false
        platforms: {{ inputs.platform }}
        tags: |
          ${{ steps.meta.outputs.tags }}
          ghcr.io/${{ inputs.image_name }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Sign the published Docker image
      if: ${{ github.event_name != 'pull_request' }}
      env:
        TAGS: |
          ${{ steps.meta.outputs.tags }}
          ghcr.io/${{ inputs.image_name }}:latest
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
      run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}